use for4laba

--включает соединение INNER JOIN этих таблиц
SELECT * FROM AUDITORIUM_TYPE INNER JOIN AUDITORIUM
	ON AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
	ORDER BY AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPE


SELECT * FROM AUDITORIUM_TYPE AS at RIGHT OUTER JOIN AUDITORIUM AS aa
	ON aa.AUDITORIUM = at.AUDITORIUM_TYPE
	ORDER BY aa.AUDITORIUM, at.AUDITORIUM_TYPE
--включает соединение INNER JOIN этих таблиц