use for4laba

--FULL OUTER JOIN = LEFT OUTER JOIN è RIGHT OUTER JOIN 
SELECT * FROM AUDITORIUM_TYPE AS at LEFT OUTER JOIN AUDITORIUM AS aa
	ON aa.AUDITORIUM = at.AUDITORIUM_TYPE
	ORDER BY aa.AUDITORIUM, at.AUDITORIUM_TYPE


SELECT * FROM AUDITORIUM_TYPE AS at RIGHT OUTER JOIN AUDITORIUM AS aa
	ON aa.AUDITORIUM = at.AUDITORIUM_TYPE
	ORDER BY aa.AUDITORIUM, at.AUDITORIUM_TYPE
--FULL OUTER JOIN = LEFT OUTER JOIN è RIGHT OUTER JOIN