use for4laba

--йнллсрюрхбмнярэ
SELECT * FROM AUDITORIUM_TYPE AS at FULL OUTER JOIN AUDITORIUM AS aa
	ON aa.AUDITORIUM = at.AUDITORIUM_TYPE
	ORDER BY aa.AUDITORIUM, at.AUDITORIUM_TYPE


SELECT * FROM AUDITORIUM AS aa FULL OUTER JOIN AUDITORIUM_TYPE AS at
	ON aa.AUDITORIUM = at.AUDITORIUM_TYPE
	ORDER BY aa.AUDITORIUM, at.AUDITORIUM_TYPE
--йнллсрюрхбмнярэ

