use UNIVER

SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPE, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME, AUDITORIUM.AUDITORIUM
From AUDITORIUM_TYPE, AUDITORIUM
	Where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE


SELECT T1.AUDITORIUM_TYPE, T1.AUDITORIUM_TYPENAME, T2.AUDITORIUM
	FROM AUDITORIUM AS T2, AUDITORIUM_TYPE AS T1
		Where T2.AUDITORIUM_TYPE = T1.AUDITORIUM_TYPE