//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECORD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECORD()
        {
            this.COMMENTS = new HashSet<COMMENTS>();
            this.ORDER_CARD_DETAILS = new HashSet<ORDER_CARD_DETAILS>();
            this.GENRE = new HashSet<GENRE>();
            this.SONG = new HashSet<SONG>();
        }
    
        public decimal RECORD_ID { get; set; }
        public Nullable<decimal> YEAR { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> SUPPLIER_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string ARTIST_NAME { get; set; }
        public string ALBUM_NAME { get; set; }
        public string PICTURE { get; set; }
        public string STATUS { get; set; }
        public string IS_DELETED { get; set; }
        public Nullable<System.DateTime> DATE_OF_DELIV_TO_WAREHOUSE { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTS> COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_CARD_DETAILS> ORDER_CARD_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENRE> GENRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SONG> SONG { get; set; }
    }
}
