import blueHawaii from "./../images/albumsMain/Elvis Presley - Blue Hawaii.jpg";
import likeAPrayer from "./../images/albumsMain/Madonna - Like a prayer .jpg";
import kino from "./../images/albumsMain/Кино - Черный альбом.jpg";
import izbrannoe from "./../images/albumsMain/Владимир Высоцкий - Избранное.jpg";
import withTheBeatles from "./../images/albumsMain/The beatles - With the beatles.jpg";
import allEyezOnMe from "./../images/albumsMain/2pac - All eyez On Me.jpg";
import frankensteinGirls from "./../images/albumsMain/Mindless Self Indulgence - Frankenstein Girls.jpg";
import akystichAlb from "./../images/albumsMain/Король и шут - Акустический альбом.jpeg";
import smirisIRasslabsya from "./../images/albumsMain/Валентин Стрыкало - Смирись и расслабься.webp";
import msiIf from "./../images/albumsMain/Mindless Self Indulgence - If.jfif";
import theFame from "./../images/albumsMain/Lady Gaga - The Fame.jpg";
import beTheCowboy from "./../images/albumsMain/Mitski - Be the cowboy.jpg";
import igor from "./../images/albumsMain/Tyler, the creator - Igor.png";
import { Genres } from "./Genres";

const InfForPages = [
  {
    id: 1,
    path: "/queenBohemianRhapsody",
    count: 0,
    back: require("./../images/backgrounds/queen.jpg"),
    image: require("./../images/albumsMain/Queen - Bohemian Rhapsody.jfif"),
    image2: require("./../images/albumsAdd/bohrhapqueen1.jpg"),
    image3: require("./../images/albumsAdd/bohrhapqueen2.jfif"),
    image4: require("./../images/albumsAdd/bohrhapqueen3.webp"),
    name: "Queen - Bohemian Rhapsody",
    article: "957396927594",
    price: "49.99$",
    sides: [
      {
        a1: "20th Century Fox Fanfare (Ft. Brian May & Roger Taylor)",
        a2: "Somebody to Love",
        a3: "Doing All Right (…Revisited) by Smile (UK)",
        a4: "Keep Yourself Alive (Live at The Rainbow)",
        a5: "Killer Queen",
        a6: "Fat Bottomed Girls (Live in Paris)",
        a7: "Bohemian Rhapsody",
        a8: "Now I'm Here",
        a9: "Crazy Little Thing Called Love",
        a10: "Love of My Life",
        a11: "We Will Rock You",
      },
      {
        b1: "Another One Bites the Dust",
        b2: "I Want to Break Free",
        b3: "Under Pressure",
        b4: "Who Wants to Live Forever",
        b5: "Bohemian Rhapsody (Reprise)",
        b6: "Radio Ga Ga",
        b7: "Ay-Oh",
        b8: "Hammer to Fall",
        b9: "We Are the Champions",
        b10: "Don't Stop Me Now... Revisited",
        b11: "Don't Stop Me Now... Revisited",
      },
    ],
    genres: {
      genre1: Genres.get("hRock"),
      genre2: Genres.get("progrPop"),
      genre3: Genres.get("progrRock"),
    },
    year: "1985",
    description: [
      "Originally released October 31, 1975 and lifted from the seminal 'A Night At The Opera' album, 'Bohemian Rhapsody' is often considered to be Queen's magnum opus and one of the all-time greatest songs, reaching the #1 spot in numerous territories (nine consecutive weeks in the UK alone).",
      <br />,
      `This grouping assembles most single releases, re-releases and bootlegs where "Bohemian Rhapsody" receives A-side/top billing. "I'm In Love With My Car" is the most-often used B-side song ("Death On Two Legs" and "Sweet Lady" being alternates).`,
      <br />,
      `There are two mixes of The B side "I'm In Love With My Car". Most releases play a remixed version (has car revs at the start of the track), but some issues (eg Canada and US) play the "A Night At The Opera" album version (with the false fade).`,
      <br />,
      `Shortly after Freddie Mercury's death in 1991 it was re-released again (and hit the #1 spot one more time) as a double-A single, grouped as QUEEN20 here.`,
    ],
  },
  {
    id: 2,
    path: "/playboiCartiDieLit",
    count: 0,
    back: require("./../images/backgrounds/playboicarti.webp"),
    image: require("./../images/albumsMain/Playboi Carti - Die Lit.jfif"),
    image2: require("./../images/albumsAdd/dielitplcarti1.png"),
    image3: require("./../images/albumsAdd/dielitplcarti2.jpg"),
    image4: require("./../images/albumsAdd/dielitplcarti3.jpg"),
    name: "Playboi Carti - Die Lit",
    article: "593759370395",
    price: "19.99$",
    sides: [
      {
        a1: "Long Time - Intro",
        a2: "R.I.P.",
        a3: "Lean 4 Real (Ft. Skepta)",
        a4: "Old Money",
        a5: "Love Hurts (Ft. Travis Scott)",
        a6: "Shoota (Ft. Lil Uzi Vert)",
        a7: "Right Now",
        a8: "Poke It Out",
        a9: "Home (KOD)",
        a10: "Fell in Luv",
      },
      {
        b1: "Foreign",
        b2: "Pull Up",
        b3: "Mileage",
        b4: "FlatBed Freestyle",
        b5: "No Time",
        b6: "Middle of the Summer",
        b7: "Choppa Won't Miss",
        b8: "R.I.P. Fredo (Notice Me)",
        b9: "Top",
      },
    ],
    genres: {
      genre1: Genres.get("hiphop"),
      genre2: Genres.get("trap"),
      genre3: Genres.get("mumbleRap"),
    },
    year: "2018",
    description: [
      "Die Lit is Playboi Carti’s debut studio album and a follow-up to his eponymous debut mixtape. The album is executively produced by Pi'erre Bourne and boasts features from Young Thug, Lil Uzi Vert, Travis Scott, Nicki Minaj, and Skepta, among many others.",
      <br />,
      "Die Lit is a reminder of the power of simplicity, as the album is full of effortless vibes and hypnotic flows that create an array of catchy, uncomplicated tracks. Carti explores different vocal inflections, and he emphasizes his Atlanta accent in his delivery.",
      <br />,
      "Before the album’s release, fifteen songs recorded during production of the album were leaked online. However, only four of the leaked tracks were actually on the album; these are “Shoota” (the leaked version was a rough demo), “Love Hurts,” “Choppa Won’t Miss,” and “Foreign.”",
      <br />,
      "On May 2, 2018, Carti officially released “Love Hurts” on SoundCloud as the album’s lead single.",
    ],
  },
  {
    id: 3,
    path: "/juiceWrldLegendsNeverDie",
    count: 0,
    back: require("./../images/backgrounds/juicewrld.webp"),
    image: require("./../images/albumsMain/Juice WRLD - Legends Never Die.jfif"),
    image2: require("./../images/albumsAdd/juiceWrldLegendsNeverDie1.jpg"),
    image3: require("./../images/albumsAdd/juiceWrldLegendsNeverDie2.jpg"),
    image4: require("./../images/albumsAdd/juiceWrldLegendsNeverDie3.jpg"),
    name: "Juice WRLD - Legends Never Die",
    article: "386039806032",
    price: "39.99$",
    sides: [
      {
        a1: "Anxiety (Intro)",
        a2: "Conversations",
        a3: "Titanic",
        a4: "Bad Energy",
        a5: "Righteous",
        a6: "Blood On My Jeans",
        a7: "Smile",
        a8: "Tell Me U Luv Me by Juice WRLD & Trippie Redd",
        a9: "Hate the Other Side by Juice WRLD & Marshmello",
        a10: "Get Through It (Interlude)",
        a11: "Life’s a Mess",
      },
      {
        b1: "Come & Go",
        b2: "I Want It",
        b3: "Fighting Demons",
        b4: "Wishing Well",
        b5: "Screw Juice",
        b6: "Up Up and Away",
        b7: "The Man, The Myth, The Legend",
        b8: "Stay High",
        b9: "Can't Die",
        b10: "Man of the Year",
      },
    ],
    genres: {
      genre1: Genres.get("emoRap"),
      genre2: Genres.get("hiphop"),
    },
    year: "2020",
    description: [
      "Juice WRLD’s first posthumous album, Legends Never Die, was originally rumored to be named The Outsiders based on a freestyle he did within an Instagram live, but was later confirmed to be Legends Never Die four days before the release.",
      <br />,
      "Additionally, during an Instagram live stream six months after his death, Juice’s girlfriend, Ally Lotti, hinted at the original album title, but seemingly delayed its release:",
      <br />,
      `"Remember we were talking about The Outsiders… That actual album, no one is ready for it. I’m not ready for it. And I promise you, you are not ready for it."`,
      <br />,
      "The first promotional single for the album was titled “Righteous“ and released in late April 2020. The following month, the label followed with the release of “Tell Me U Luv Me,“ another single with frequent collaborator Trippie Redd.",
      <br />,
      "Multiple demos of the album surfaced on the internet in early 2020 and consisted of up to 30 of his tracks, such as “Righteous,“ “Bad Boy,“ and “Tell Me U Luv Me.“ However, none of these tracks were officially confirmed to be on the album.",
      <br />,
      "In the first few weeks of June, Juice’s label teased snippets for multiple tracks such as “Cake,“ “Molly & Mike,“ and “Don’t Understand,“ hinting at their possible releases within the album. However, the only confirmed track was the highly anticipated “Blood on My Jeans“, which was confirmed by Juice’s label manager Lil Bibby when he responded to a fan on Instagram.",
      <br />,
      "On July 6, 2020, Juice’s label took to Juice’s Twitter to officially confirm the release date of the album to be July 10, and officially confirmed the album title to be Legends Never Die with a small teaser video.",
      <br />,
      "A few hours later, the label once again took to social media on the same day to put out a message for the public honoring Juice, whilst also releasing the official cover art for Legends Never Die.",
    ],
  },
  {
    id: 4,
    path: "/scarlxrdDxxm2",
    count: 0,
    back: require("./../images/backgrounds/scarlxrd.jpg"),
    image: require("./../images/albumsMain/Scarlxrd - Dxxm2.png"),
    image2: require("./../images/albumsAdd/evilEgx.jfif"),
    image3: require("./../images/albumsAdd/letTheWxrldBurn.jpg"),
    image4: require("./../images/albumsAdd/redLight.jpg"),
    name: "Scarlxrd - DXXM II",
    article: "486948593068",
    price: "24.99$",
    sides: [
      {
        a1: "Apxcalypse",
        a2: "Kill Xr Be Killed",
        a3: "Leeches!!!",
        a4: "Shh!...",
        a5: "Ngafiyd",
        a6: "Drxwn 6x",
        a7: "Destrxy the Cure",
        a8: "Nx Chance Xf Survival",
        a9: "Rxbxt Slut",
        a10: "Natural Selectixn",
        a11: "Utxpia = Mass Genxcide",
      },
      {
        b1: "Stand Yxur Grxund",
        b2: "Dx I Still Dream?",
        b3: "Cautixn",
        b4: "Serxtxnin",
        b5: "Evil Egx",
        b6: "Red Light",
        b7: "Let the Wxrld Burn",
        b8: "Nightmares",
        b9: "Get Him!",
        b10: "Gx Kill Yxurself",
      },
    ],
    genres: {
      genre1: Genres.get("altRock"),
      genre2: Genres.get("hardcoreRap"),
      genre3: Genres.get("trap"),
    },
    year: "2021",
    description: [
      "Dxxm II is the long-anticipated twelfth studio album by Scarlxrd. It is also his first project since once again, going independent, having left Universal Records a couple of months prior to the drop. The album acts as a direct descendant of the previously mentioned “DXXM”, arguably, Scarlxrd’s most successful and best received album to date.",
      <br />,
      "Along side the album, Scarlxrd launched his own Techwear brand by the similar name “DXXMLIFE” on 27 November 2020, which was followed by a restock on 26 December 2020.",
      <br />,
      "He would use this brands trailers as a means to tease tracks such as “Get Him!”.",
    ],
  },
  {
    id: 5,
    path: "/travisScottAstroworld",
    count: 0,
    back: require("./../images/backgrounds/travisScott.jpg"),
    image: require("./../images/albumsMain/Travis Scott - Astroworld.jfif"),
    image2: require("./../images/albumsAdd/astrotravisscott1.webp"),
    image3: require("./../images/albumsAdd/astrotravisscott2.jpeg"),
    image4: require("./../images/albumsAdd/astrotravisscott3.jpg"),
    name: "Travis Scott - Astroworld",
    article: "402950830593",
    price: "19.99$",

    sides: [
      {
        a1: "Stargazing",
        a2: "Carousel",
        a3: "Sicko Mode",
        a4: "R.I.P. Screw",
        a5: "Stop Trying to Be God",
        a6: "No Bystanders",
        a7: "Skeletons",
        a8: "Wake Up",
        a9: "5% Tint",
      },
      {
        b1: "NC-17",
        b2: "Astrothunder",
        b3: "Yosemite",
        b4: "Can't Say",
        b5: "Who? What!",
        b6: "Butterfly Effect",
        b7: "Houstonfornication",
        b8: "Coffee Bean",
      },
    ],
    genres: {
      genre1: Genres.get("hiphop"),
      genre2: Genres.get("psRap"),
      genre3: Genres.get("rap"),
    },
    year: "2018",
    description: [
      "ASTROWORLD is Travis Scott’s long-awaited third studio album, following his 2016 release Birds in the Trap Sing McKnight. The album is titled after Six Flags AstroWorld, a popular Houston amusement park. The park was demolished in 2005. Despite several developers staking claims to develop the large vacant lot into use, nothing has been done with the space since. In a 2017 interview with GQ, Travis lamented on the park’s prominence in Houston and its impact on the album:",
      <br />,
      `"That’s what it’s going to sound like, like taking an amusement park away from kids. We want it back. We want the building back. That’s why I’m doing it. It took the fun out of the city."`,
      <br />,
      "Travis initially confirmed the title in a May 2016 show, stating that it would follow BITTSM. Almost two years later, he released a promotional single for the album – “Watch” – which features guest vocals from Lil Uzi Vert and Kanye West. However, the song did not make the album, with his platinum single “BUTTERFLY EFFECT” appearing instead.",
      <br />,
      "Scott confirmed that the album is a sequel to his 2015 album Rodeo, saying:",
      <br />,
      `"My whole idea was, if you locked into Rodeo, you definitely locked into ASTROWORLD. I’m just finishing the saga I started on my first album. This is supposed to be my second album. I had to go quick, because like I said, I had all these ideas, I just had to get off real quick, but now I’m finally back home with ASTROWORLD."`,
      <br />,
      "In early July, Travis Scott assembled a “supergroup” of artists and producers in Hawaii to finish the album.",
      <br />,
      "Leading up to the announcement of the album’s release date, gold inflatable Travis Scott heads popped up in various locations, including Amoeba Music in Los Angeles, Minute Maid Park in Houston (home to the Houston Astros), and on top of the Hard Rock Cafe in NYC’s Times Square.",
      <br />,
      "The inflatable head ended up being an integral part of the album’s artwork, which was announced on July 31st, days before the album’s release on August 3rd.",
      <br />,
      "On December 7th, 2018, the album was nominated for the GRAMMY’s best rap album of 2018. Additionally, the hit “SICKO MODE” was nominated for both the best rap song and the best rap performance. Travis expressed his gratitude the next day, saying:",
      <br />,
      `"Thank u record academy it’s took a whole 24hrs for it to really hit me. Plus this has Also been my duffle all year."`,
    ],
  },
  {
    id: 6,
    path: "/futureHighOffLife",
    count: 0,
    back: require("./../images/backgrounds/future.jpg"),
    image: require("./../images/albumsMain/Future - High Off Life .jpg"),
    image2: require("./../images/albumsAdd/highofflifefuture1.jpg"),
    image3: require("./../images/albumsAdd/highofflifefuture2.png"),
    image4: require("./../images/albumsAdd/highofflifefuture3.jpg"),
    name: "Future - High Off Life",
    article: "195830691058",
    price: "19.99$",
    sides: [
      {
        a1: "Trapped in the Sun",
        a2: "HiTek Tek",
        a3: "Touch the Sky",
        a4: "Solitaires",
        a5: "Ridin Strikers",
        a6: "One of My",
        a7: "Posted with Demons",
        a8: "Hard to Choose One",
        a9: "Trillionaire",
        a10: "Harlem Shake",
        a11: "Up the River",
      },
      {
        b1: "Pray for a Key",
        b2: "Too Comfortable",
        b3: "All Bad",
        b4: "Outer Space Bih",
        b5: "Accepting My Flaws",
        b6: "Life Is Good",
        b7: "Last Name",
        b8: "Tycoon",
        b9: "100 Shooters",
        b10: "Life Is Good (Remix)",
      },
    ],
    genres: {
      genre1: Genres.get("hiphop"),
      genre2: Genres.get("rNb"),
      genre3: Genres.get("rap"),
    },
    year: "2020",
    description: [
      "High Off Life is Future’s eighth studio album and the follow-up to January 2019’s The WIZRD.",
      <br />,
      "On July 12, 2019, Future released the album’s lead single, “100 Shooters.” Eleven days later, Future released another single, “Undefeated.” Its cover used a similar aesthetic to “Shooters,” but it was only a promotional single.",
      <br />,
      "The second single, “Last Name,” was released on November 15.",
      <br />,
      "On January 10, 2020, Future released the record’s third single, “Life Is Good,” which was a notable reunion with Drake. After a successful debut, the song received an official remix a month later, adding Lil Baby and DaBaby to the track. The remix serves as the fourth single.",
      <br />,
      "The fifth and final pre-release single, “Tycoon,” was released on April 1.",
      <br />,
      "All of the five pre-release singles were listed at the end of the album, so the first sixteen tracks are the true album while the five singles are bonus tracks.",
      <br />,
      "On April 7, 2020, XXL published their interview with Future for their Spring 2020 issue. Future initially stated that Life Is Good was the album’s title. He also described its creative process and what the album meant to him.",
      <br />,
      "On May 12, 2020, DJ ESCO, the album’s executive producer, officially announced the LP by posting its tracklist on his Instagram. This revealed that the album’s title had been changed to High Off Life. Hours later, Future confirmed the album via a tweet, and he also posted the official artwork.",
    ],
  },
  {
    id: 7,
    path: "/scarlxrdImmxrtalisatixn",
    count: 0,
    back: require("./../images/backgrounds/scarlxrd.jpg"),
    image: require("./../images/albumsMain/Scarlxrd - Immxrtalisatixn.jfif"),
    image2: require("./../images/albumsAdd/immxrtalisatixn1.jpg"),
    image3: require("./../images/albumsAdd/immxrtalisatixn2.jpg"),
    image4: require("./../images/albumsAdd/immxrtalisatixn3.jpg"),
    name: "Scarlxrd - Immxrtalisatixn",
    article: "970496930693",
    price: "19.99$",
    sides: [
      {
        a1: "XMG",
        a2: "UP. UP. UP.",
        a3: "MXNDAY MXRNING",
        a4: "GXING THE DISTANCE",
        a5: "ASK",
        a6: "00007",
        a7: "NIKEFACE",
        a8: "WINNING",
        a9: "NX LXVE",
        a10: "BEASTMXDE",
        a11: "KILL CXNFIRMED.",
        a12: "STEALTH",
      },
      {
        b1: "GXLD",
        b2: "PRXBLEMATIC",
        b3: "EGX DEATH!",
        b4: "LXWKEY",
        b5: "PRXSPER",
        b6: "I WANT 1 BILLIXN PXUNDS",
        b7: "NXT MY BUSINESS",
        b8: "BACKWARDS",
        b9: "RUTHLESS",
        b10: "HXUSE XF LXRDS",
        b11: "I DXNT NEED TX KNXW",
        b12: "SEARCH & DESTRXY",
      },
    ],
    genres: {
      genre1: Genres.get("trMetall"),
      genre2: Genres.get("hCore"),
      genre3: Genres.get("rapRock"),
    },
    year: "2019",
    description: [
      "IMMXRTALISATIXN is Scarlxrd’s eighth studio album, released on October 4, 2019, along with 8 songs that didn’t make the album as the THRXWAWAYS AS PRXMISED. EP.",
    ],
  },
  {
    id: 8,
    path: "/michaelJacksonBad",
    count: 0,
    back: require("./../images/backgrounds/michaelJackson.jpg"),
    image: require("./../images/albumsMain/Michael Jackson - Bad.jfif"),
    image2: require("./../images/albumsAdd/badMichaelJackson1.jpg"),
    image3: require("./../images/albumsAdd/badMichaelJackson2.jpg"),
    image4: require("./../images/albumsAdd/badMichaelJackson3.webp"),
    name: "Michael Jackson - Bad",
    article: "394820481107",
    price: "49.99$",
    sides: [
      {
        a1: "Bad",
        a2: "The Way You Make Me Feel",
        a3: "Speed Demon",
        a4: "Liberian Girl",
        a5: "Just Good Friends (Ft. Stevie Wonder)",
        a6: "Leave Me Alone",
      },
      {
        b1: "Another Part of Me",
        b2: "Man in the Mirror",
        b3: "I Just Can't Stop Loving You (Ft. Siedah Garrett)",
        b4: "Dirty Diana",
        b5: "Smooth Criminal",
      },
    ],
    genres: {
      genre1: Genres.get("pop"),
      genre2: Genres.get("rock"),
      genre3: Genres.get("hRock"),
      genre4: Genres.get("dance"),
      genre5: Genres.get("rNb"),
      genre6: Genres.get("soul"),
      genre7: Genres.get("funk"),
    },
    year: "1987",
    description: [
      "Following the colossal success of 1982’s Thriller, it took five years for Michael Jackson to release his highly anticipated follow-up, 1987’s Bad. He once again collaborated with producer Quincy Jones as he did for Thriller and 1979’s Off the Wall, but this would be their last time working together. This final installment of the Jackson/Jones trilogy was another massive hit, selling millions of albums worldwide along with achieving more awards and accolades.",
      <br />,
      "Michael reportedly started demos for the album as early as November 1983 while he was working on the Victory album with his brothers The Jacksons. He would also create songs at his home studio and bring them into the Westlake Audio studio in Los Angeles to be re-produced and re-mixed by Quincy Jones and engineer Bruce Swedien. The recording process began in January 1985, around the time Michael co-wrote and Quincy produced the all-star charity single “We Are the World.” The recording sessions wrapped in July 1987, with “I Just Can’t Stop Loving You” being released as the first single the same month before the album’s August release.",
      <br />,
      'Like Thriller, Bad was a mix of R&B, Rock, Pop, and ballads that once again provided the formula to top the pop charts internationally. It has sold approximately 35 million records worldwide and is certified Diamond status with more than 11 million copies sold in the US, where the album sold over 2 million copies in its first week. Of the album’s 11 songs, nine were released as singles and the album was the first to produce five #1 pop singles on the Billboard Hot 100—"I Just Can’t Stop Loving You,“ "Bad,” “The Way You Make Me Feel,” “Man in the Mirror” and “Dirty Diana.” “Smooth Criminal” and “Another Part of Me” were Top 20 singles, while “Leave Me Alone” and “Liberian Girl” were also released as singles, which both topped the pop charts in Ireland. The film Moonwalker was released in 1988 and featured several music videos from Bad. This film led to a Moonwalker video game being released for the Sega Genesis console in 1990 and it was based around the visuals from “Smooth Criminal.”',
    ],
  },
  {
    id: 9,
    path: "/elvisPresleyBlueHawaii",
    count: 0,
    back: require("./../images/backgrounds/elvisPresley.jpg"),
    image: require("./../images/albumsMain/Elvis Presley - Blue Hawaii.jpg"),
    image2: require("./../images/albumsAdd/blueHawaiiElvis1.jfif"),
    image3: require("./../images/albumsAdd/blueHawaiiElvis2.jpg"),
    image4: require("./../images/albumsAdd/blueHawaiiElvis3.jfif"),
    name: "Elvis Presley - Blue Hawaii",
    article: "394800283699",
    price: "29.99$",
    sides: [
      {
        a1: "Blue Hawaii",
        a2: "Almost Always True",
        a3: "Aloha 'Oe",
        a4: "No More",
        a5: "Can't Help Falling in Love",
        a6: "Rock-A-Hula Baby",
        a7: "Moonlight Swim",
      },
      {
        b1: "Ku-U-I-Po",
        b2: "Ito Eats",
        b3: "Slicin' Sand",
        b4: "Hawaiian Sunset",
        b5: "Beach Boy Blues",
        b6: "Island of Love",
        b7: "Hawaiian Wedding Song",
      },
    ],
    genres: {
      genre1: Genres.get("pop"),
      genre2: Genres.get("rockandroll"),
    },
    year: "1961",
    description: [
      "Blue Hawaii is the fourth soundtrack album by the American singer Elvis Presley, released on RCA Victor Records in mono and stereo, LPM/LSP 2426, on October 20, 1961.[6] It is the soundtrack to the 1961 film of the same name starring Presley. In the United States, the album spent 20 weeks at the number one slot and 39 weeks in the Top 10 on Billboard's Top Pop LPs chart. It was certified Gold on December 21, 1961, Platinum and 2× Platinum on March 27, 1992, and 3× Platinum on July 30, 2002, by the Recording Industry Association of America.[7] On the US Top Pop Albums chart, Blue Hawaii is second only to the soundtrack of West Side Story as the most successful soundtrack album of the 1960s.",
    ],
  },
  {
    id: 10,
    path: "/msiIf",
    count: 0,
    back: require("./../images/backgrounds/Mindless Self Indulgence.jpg"),
    image: require("./../images/albumsMain/Mindless Self Indulgence - If.jfif"),
    image2: require("./../images/albumsAdd/if1.jpg"),
    image3: require("./../images/albumsAdd/if2.jpg"),
    image4: require("./../images/albumsAdd/if3.jpg"),
    name: "Mindless Self Indulgence - If",
    article: "485938409330",
    price: "19.99$",
    sides: [
      {
        a1: "Never Wanted to Dance",
        a2: "Evening Wear",
        a3: "Lights Out",
        a4: "Prescription",
        a5: "Issues",
        a6: "Get it Up",
        a7: "Revenge",
        a8: "Animal",
      },
      {
        b1: "Mastermind",
        b2: "On It",
        b3: "Pay for It",
        b4: "Due",
        b5: "Money",
        b6: "Bomb This Track",
        b7: "Mark David Chapman",
      },
    ],
    genres: {
      genre1: Genres.get("synthPunk"),
      genre2: Genres.get("elRock"),
      genre3: Genres.get("dancePunk"),
    },
    year: "2008",
    description: [
      "If is the fourth studio album by Mindless Self Indulgence. It was released through The End Records on April 28, 2008 in the UK and on April 29, 2008 in the U.S. The album debuted on Billboard's Top 200 Album Sales Chart at #27.",
    ],
  },
  {
    id: 11,
    path: "/msiYoullRebelToAnything",
    count: 0,
    back: require("./../images/backgrounds/Mindless Self Indulgence.jpg"),
    image: require("./../images/albumsMain/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING.jfif"),
    image2: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING1.jfif"),
    image3: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING2.jpg"),
    image4: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING3.jpg"),
    name: "Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING",
    article: "148602845391",
    price: "19.99$",
    sides: [
      {
        a1: "Shut Me Up",
        a2: "1989",
        a3: "Straight to Video",
        a4: "Tom Sawyer",
        a5: "You'll Rebel To Anything",
        a6: "What Do They Know?",
      },
      {
        b1: "Stupid MF",
        b2: "2 Hookers and an Eightball",
        b3: "Prom",
        b4: "Bullshit",
        b5: "Mic Commander",
      },
    ],
    genres: {
      genre1: Genres.get("altRock"),
      genre2: Genres.get("indRock"),
      genre3: Genres.get("elRock"),
      genre4: Genres.get("synthPunk"),
    },
    year: "2005",
    description: [
      "You’ll Rebel To Anything is an album by Mindless Self Indulgence released in the United States on April 12, 2005 on CD, Vinyl, and a clean version of the CD. This album is the first studio album that current bass player Lyn-Z is on, and that is not the only first this album has. Just as an example, this was the first album to hit the Billboard Top 200 charts when it was released, reaching a peak position of 107.",
    ],
  },
  {
    id: 12,
    path: "/msiYoullRebelToAnything",
    count: 0,
    back: require("./../images/backgrounds/Mindless Self Indulgence.jpg"),
    image: require("./../images/albumsMain/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING.jfif"),
    image2: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING1.jfif"),
    image3: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING2.jpg"),
    image4: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING3.jpg"),
    name: "Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING",
    article: "148602845391",
    price: "19.99$",
    sides: [
      {
        a1: "Shut Me Up",
        a2: "1989",
        a3: "Straight to Video",
        a4: "Tom Sawyer",
        a5: "You'll Rebel To Anything",
        a6: "What Do They Know?",
      },
      {
        b1: "Stupid MF",
        b2: "2 Hookers and an Eightball",
        b3: "Prom",
        b4: "Bullshit",
        b5: "Mic Commander",
      },
    ],
    genres: {
      genre1: Genres.get("altRock"),
      genre2: Genres.get("indRock"),
      genre3: Genres.get("elRock"),
      genre4: Genres.get("synthPunk"),
    },
    year: "2005",
    description: [
      "You’ll Rebel To Anything is an album by Mindless Self Indulgence released in the United States on April 12, 2005 on CD, Vinyl, and a clean version of the CD. This album is the first studio album that current bass player Lyn-Z is on, and that is not the only first this album has. Just as an example, this was the first album to hit the Billboard Top 200 charts when it was released, reaching a peak position of 107.",
    ],
  },
  {
    id: 13,
    path: "/msiYoullRebelToAnything",
    count: 0,
    back: require("./../images/backgrounds/Mindless Self Indulgence.jpg"),
    image: require("./../images/albumsMain/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING.jfif"),
    image2: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING1.jfif"),
    image3: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING2.jpg"),
    image4: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING3.jpg"),
    name: "Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING",
    article: "148602845391",
    price: "19.99$",
    sides: [
      {
        a1: "Shut Me Up",
        a2: "1989",
        a3: "Straight to Video",
        a4: "Tom Sawyer",
        a5: "You'll Rebel To Anything",
        a6: "What Do They Know?",
      },
      {
        b1: "Stupid MF",
        b2: "2 Hookers and an Eightball",
        b3: "Prom",
        b4: "Bullshit",
        b5: "Mic Commander",
      },
    ],
    genres: {
      genre1: Genres.get("altRock"),
      genre2: Genres.get("indRock"),
      genre3: Genres.get("elRock"),
      genre4: Genres.get("synthPunk"),
    },
    year: "2005",
    description: [
      "You’ll Rebel To Anything is an album by Mindless Self Indulgence released in the United States on April 12, 2005 on CD, Vinyl, and a clean version of the CD. This album is the first studio album that current bass player Lyn-Z is on, and that is not the only first this album has. Just as an example, this was the first album to hit the Billboard Top 200 charts when it was released, reaching a peak position of 107.",
    ],
  },
  {
    id: 14,
    path: "/msiYoullRebelToAnything",
    count: 0,
    back: require("./../images/backgrounds/Mindless Self Indulgence.jpg"),
    image: require("./../images/albumsMain/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING.jfif"),
    image2: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING1.jfif"),
    image3: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING2.jpg"),
    image4: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING3.jpg"),
    name: "Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING",
    article: "148602845391",
    price: "19.99$",
    sides: [
      {
        a1: "Shut Me Up",
        a2: "1989",
        a3: "Straight to Video",
        a4: "Tom Sawyer",
        a5: "You'll Rebel To Anything",
        a6: "What Do They Know?",
      },
      {
        b1: "Stupid MF",
        b2: "2 Hookers and an Eightball",
        b3: "Prom",
        b4: "Bullshit",
        b5: "Mic Commander",
      },
    ],
    genres: {
      genre1: Genres.get("altRock"),
      genre2: Genres.get("indRock"),
      genre3: Genres.get("elRock"),
      genre4: Genres.get("synthPunk"),
    },
    year: "2005",
    description: [
      "You’ll Rebel To Anything is an album by Mindless Self Indulgence released in the United States on April 12, 2005 on CD, Vinyl, and a clean version of the CD. This album is the first studio album that current bass player Lyn-Z is on, and that is not the only first this album has. Just as an example, this was the first album to hit the Billboard Top 200 charts when it was released, reaching a peak position of 107.",
    ],
  },
  {
    id: 15,
    path: "/msiYoullRebelToAnything",
    count: 0,
    back: require("./../images/backgrounds/Mindless Self Indulgence.jpg"),
    image: require("./../images/albumsMain/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING.jfif"),
    image2: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING1.jfif"),
    image3: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING2.jpg"),
    image4: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING3.jpg"),
    name: "Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING",
    article: "148602845391",
    price: "19.99$",
    sides: [
      {
        a1: "Shut Me Up",
        a2: "1989",
        a3: "Straight to Video",
        a4: "Tom Sawyer",
        a5: "You'll Rebel To Anything",
        a6: "What Do They Know?",
      },
      {
        b1: "Stupid MF",
        b2: "2 Hookers and an Eightball",
        b3: "Prom",
        b4: "Bullshit",
        b5: "Mic Commander",
      },
    ],
    genres: {
      genre1: Genres.get("altRock"),
      genre2: Genres.get("indRock"),
      genre3: Genres.get("elRock"),
      genre4: Genres.get("synthPunk"),
    },
    year: "2005",
    description: [
      "You’ll Rebel To Anything is an album by Mindless Self Indulgence released in the United States on April 12, 2005 on CD, Vinyl, and a clean version of the CD. This album is the first studio album that current bass player Lyn-Z is on, and that is not the only first this album has. Just as an example, this was the first album to hit the Billboard Top 200 charts when it was released, reaching a peak position of 107.",
    ],
  },
  {
    id: 16,
    path: "/msiYoullRebelToAnything",
    count: 0,
    back: require("./../images/backgrounds/Mindless Self Indulgence.jpg"),
    image: require("./../images/albumsMain/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING.jfif"),
    image2: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING1.jfif"),
    image3: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING2.jpg"),
    image4: require("./../images/albumsAdd/Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING3.jpg"),
    name: "Mindless Self Indulgence - YOU'LL REBEL TO ANYTHING",
    article: "148602845391",
    price: "19.99$",
    sides: [
      {
        a1: "Shut Me Up",
        a2: "1989",
        a3: "Straight to Video",
        a4: "Tom Sawyer",
        a5: "You'll Rebel To Anything",
        a6: "What Do They Know?",
      },
      {
        b1: "Stupid MF",
        b2: "2 Hookers and an Eightball",
        b3: "Prom",
        b4: "Bullshit",
        b5: "Mic Commander",
      },
    ],
    genres: {
      genre1: Genres.get("altRock"),
      genre2: Genres.get("indRock"),
      genre3: Genres.get("elRock"),
      genre4: Genres.get("synthPunk"),
    },
    year: "2005",
    description: [
      "You’ll Rebel To Anything is an album by Mindless Self Indulgence released in the United States on April 12, 2005 on CD, Vinyl, and a clean version of the CD. This album is the first studio album that current bass player Lyn-Z is on, and that is not the only first this album has. Just as an example, this was the first album to hit the Billboard Top 200 charts when it was released, reaching a peak position of 107.",
    ],
  },
];

export default InfForPages;
