use UNIVER

SELECT PULPIT.PULPIT_NAME[Кафедра],FACULTY.FACULTY [Факультет],PROFESSION.PROFESSION_NAME [Специальность]
	FROM FACULTY, PULPIT, PROFESSION
	Where FACULTY.FACULTY = PULPIT.FACULTY
    AND
      FACULTY.FACULTY=PROFESSION.FACULTY
    AND
    PROFESSION_NAME IN (SELECT PROFESSION.PROFESSION_NAME FROM PROFESSION Where ( PROFESSION.PROFESSION_NAME Like '%технологи%') )