use UNIVER

SELECT PULPIT.PULPIT_NAME[Кафедра],FACULTY.FACULTY [Факультет],PROFESSION.PROFESSION_NAME [Специальность]
	FROM PULPIT INNER JOIN FACULTY ON FACULTY.FACULTY = PULPIT.FACULTY
			INNER JOIN PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
	Where PROFESSION_NAME IN (SELECT PROFESSION_NAME FROM PROFESSION Where (PROFESSION_NAME Like '%технологи%'));