use UNIVER

SELECT AUDITORIUM_CAPACITY, AUDITORIUM, AUDITORIUM_TYPE
	FROM AUDITORIUM AS a
		Where AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM AS aa
			Where aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
				ORDER BY AUDITORIUM_CAPACITY DESC)
ORDER BY AUDITORIUM_CAPACITY DESC