use UNIVER

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_CAPACITY
	FROM AUDITORIUM
		Where AUDITORIUM.AUDITORIUM_CAPACITY >= any (SELECT AUDITORIUM.AUDITORIUM_CAPACITY 
														FROM AUDITORIUM
															Where AUDITORIUM.AUDITORIUM Like '4%')