use UNIVER

SELECT AUDITORIUM_TYPENAME,
	   MAX(AUDITORIUM_CAPACITY) [Максимальная вместимость],
	   MIN(AUDITORIUM_CAPACITY) [Минимальная вместимость],
	   AVG(AUDITORIUM_CAPACITY) [Средняя вместимость],
	   SUM(AUDITORIUM_CAPACITY) [Суммарная вместимость],
	   COUNT(AUDITORIUM_CAPACITY) [Общая вместимость]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
		GROUP BY AUDITORIUM_TYPENAME