version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:123@db:5432/course_proj_test
    depends_on:
      - db
    volumes:
      - ./server:/app

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: course_proj_test
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
