@hostname=localhost
@port=7058
GET http://{{hostname}}:{{port}}/Parm/Index?Id=3
###
GET http://{{hostname}}:{{port}}/Start/One
###
GET http://{{hostname}}:{{port}}/Start/Two
###
GET http://{{hostname}}:{{port}}/Start/Three
###
POST http://{{hostname}}:{{port}}/Start/Index
###
POST http://{{hostname}}:{{port}}/Start/One
###
POST http://{{hostname}}:{{port}}/Start/Two
###
POST http://{{hostname}}:{{port}}/Start/Three
###